accent = "#84b1d1"
cursor = "#fbfefe"
foreground = "#fbfefe"
background = "#201E1C"
selection_foreground = "#fbfefe"
selection_background = "#84b1d1"

color0 = "#39180d"
color1 = "#f26736"
color2 = "#56bce1"
color3 = "#bfb187"
color4 = "#84b1d1"
color5 = "#e0a285"
color6 = "#96c9df"
color7 = "#b5e1e8"
color8 = "#5b492e"
color9 = "#fba788"
color10 = "#a2dcf1"
color11 = "#dfd1c3"
color12 = "#c6dceb"
color13 = "#f4dacd"
color14 = "#dbeef5"
color15 = "#fbfefe"
